### ISSUE TITLE
Consider a time-series database

### ISSUE THREAD

**Issue by dandv** [joliveros/save-exchange-data#1]
[More suited](http://stackoverflow.com/questions/9815234/how-to-store-7-3-billion-rows-of-market-data-optimized-to-be-read/39475372#39475372) to this type of application than a RDBMS.

**Comment by joliveros** [comment]
Excellent idea! thank you

I went with influxdb. It was easy to setup with docker. I'm already up and running!

so thanks again!

https://github.com/joliveros/save-exchange-data/pull/2

**Comment by dandv** [comment]
You're welcome! An upvote on SO would be appreciated (the link was my answer), but instead of that answer, I'd prefer an upvote on [this neglected one](http://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep/39914235#39914235). Thanks in advance!
